[package]
name = "maev"
version = "0.1.0"
edition = "2021"
authors = [ "Caden Henrich <cadenhenrich@gmail.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.17.0"
